#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
TOTAL_MINUTES=8

banner "Instagram session setup"

stage "Preflight checks" 1
say "This wizard creates an Instaloader session in the API container's persistent data volume."
step "Run it from the Dokploy terminal for the API container, not from the host shell."

if ! command -v python3 >/dev/null 2>&1; then
  warn "python3 is not installed in this container."
  exit 1
fi

if ! python3 -c "import instaloader" >/dev/null 2>&1; then
  warn "The Python package 'instaloader' is not installed in this container."
  exit 1
fi

SESSION_FILE="${INSTAGRAM_SESSION_FILE:-/app/data/instagram-session}"
SESSION_DIR=$(dirname "$SESSION_FILE")
if [[ ! -d "$SESSION_DIR" ]]; then
  warn "Session directory does not exist: $SESSION_DIR"
  note "In this project the persistent Docker volume should be mounted at /app/data."
  exit 1
fi
if [[ ! -w "$SESSION_DIR" ]]; then
  warn "Session directory is not writable: $SESSION_DIR"
  exit 1
fi

say "Session destination: $SESSION_FILE"
note "The session contains authentication cookies and will be restricted to the file owner."
pause "Preflight passed. Press Enter to continue."

stage "Instagram login" 6
if [[ -n "${INSTAGRAM_USERNAME:-}" ]]; then
  say "Using INSTAGRAM_USERNAME from the container environment: $INSTAGRAM_USERNAME"
else
  ask INSTAGRAM_USERNAME "Instagram username (without @):"
fi

if [[ -z "$INSTAGRAM_USERNAME" || ! "$INSTAGRAM_USERNAME" =~ ^[A-Za-z0-9._]{1,30}$ ]]; then
  warn "Invalid Instagram username. Use 1-30 letters, numbers, periods, or underscores."
  exit 1
fi

if [[ -s "$SESSION_FILE" ]]; then
  warn "A session file already exists at $SESSION_FILE."
  if ! confirm "Replace the existing session with a new login?"; then
    say "Existing session kept unchanged."
    note "Re-run this wizard and answer 'y' if the session has expired."
    SKIP_LOGIN=1
  else
    SKIP_LOGIN=0
  fi
else
  SKIP_LOGIN=0
fi

if (( ! SKIP_LOGIN )); then
  step "Enter the Instagram password when Python prompts. Input is hidden and never saved."
  step "If two-factor authentication is enabled, enter the current six-digit code."
  python3 - "$INSTAGRAM_USERNAME" "$SESSION_FILE" <<'PY'
import getpass
import os
import sys

import instaloader

username, session_file = sys.argv[1:3]
loader = instaloader.Instaloader(
    download_pictures=False,
    download_videos=False,
    download_video_thumbnails=False,
    download_geotags=False,
    download_comments=False,
    save_metadata=False,
    compress_json=False,
    post_metadata_txt_pattern="",
    max_connection_attempts=1,
    request_timeout=30.0,
)

password = getpass.getpass("Instagram password: ")
if not password:
    raise SystemExit("Password cannot be empty.")

try:
    loader.login(username, password)
except instaloader.exceptions.TwoFactorAuthRequiredException:
    code = input("Two-factor authentication code: ").strip().replace(" ", "")
    if not code:
        raise SystemExit("Two-factor authentication code cannot be empty.")
    loader.two_factor_login(code)
finally:
    password = ""

logged_in_as = loader.test_login()
if logged_in_as is None:
    raise SystemExit("Instagram login did not produce a valid authenticated session.")
if logged_in_as.casefold() != username.casefold():
    raise SystemExit(
        f"Instagram authenticated as {logged_in_as!r}, expected {username!r}."
    )

loader.save_session_to_file(session_file)
os.chmod(session_file, 0o600)
PY
fi

if [[ ! -s "$SESSION_FILE" ]]; then
  warn "Session file was not created or is empty: $SESSION_FILE"
  exit 1
fi
chmod 600 "$SESSION_FILE"
say "Session file is ready and restricted to permission 600."

stage "Dokploy environment" 1
say "Add or update these values in Dokploy → API service → Environment:"
printf '\n'
printf '  INSTAGRAM_USERNAME=%s\n' "$INSTAGRAM_USERNAME"
printf '  INSTAGRAM_SESSION_FILE=%s\n' "$SESSION_FILE"
printf '  INSTAGRAM_PASSWORD=\n'
printf '\n'
warn "Do not copy the session file contents into Dokploy or Git."
step "Save the Dokploy environment variables."
step "Redeploy or restart the API service."
step "On an Instaloader fallback scrape, confirm the log says: Loaded Instagram session for $INSTAGRAM_USERNAME"
pause "Press Enter after recording the environment values."

finish
